all:
  children:
    webserver2:
      hosts:
        vm3:
          ansible_host: "{{ IP_VM3 }}"
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
    serverftp:
      hosts:
        vm6:
          ansible_host: "{{ IP_VM6 }}"
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
    wordpress:
      hosts:
        vm9:
          ansible_host: "{{ IP_VM9_1 }}"
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
    serverdns:
      hosts:
        vm10:
          ansible_host: "{{ IP_VM10 }}"
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
